// 预期 schema 注册表（任务卡 P1-04，验收 ID A-P1-DB）。
// 这不是第二份业务定义：列与索引清单是 migrations/ 的机器可读投影，
// 由 apps/worker/src/storage/schema.test.ts 与真实 sqlite_master 逐项比对。
// 修改 migrations 必须新增迁移并同步本表；CHECK 枚举值一律引用 packages/contracts
// 的单一定义源（AGENTS.md 硬规则 3），未收编进 contracts 的合同字面枚举单独标注出处。
import {
  DELIVERY_STATUSES,
  EVENT_STATUSES,
  EVENT_TYPES,
  NODE_TYPES,
  REVIEW_STATUSES,
  SESSION_STATUSES,
  SUBSCRIPTION_STATES,
  TIME_BASES,
  TIME_PRECISIONS,
} from "../../../../packages/contracts/src/enums";

/** 各表列全集（与 CREATE TABLE 逐列一致；不含系统 rowid）。 */
export const EXPECTED_TABLES: Record<string, readonly string[]> = {
  // 数据组 1：来源与正文
  sources: [
    "source_id",
    "game",
    "region",
    "adapter",
    "approved_hosts_json",
    "verified_publishers_json",
    "cursor_json",
    "poll_policy_json",
    "verification_state",
    "last_success_at",
    "created_at",
    "updated_at",
  ],
  articles: [
    "id",
    "source_id",
    "external_id",
    "official_url",
    "first_seen_at",
    "last_checked_at",
    "created_at",
    "updated_at",
  ],
  article_versions: [
    "id",
    "article_id",
    "version_no",
    "content_hash",
    "body_blocks_json",
    "media_refs_json",
    "completeness",
    "official_published_at",
    "fetched_at",
    "created_at",
  ],
  // 数据组 2：理解与事实
  events: [
    "id",
    "game",
    "region",
    "event_type",
    "status",
    "title",
    "summary",
    "official_url",
    "detail_path",
    "event_revision",
    "schedule_revision",
    "human_locked",
    "first_published_at",
    "created_at",
    "updated_at",
  ],
  milestones: [
    "id",
    "event_id",
    "milestone_key",
    "node_type",
    "title",
    "time_exact_ms",
    "time_date",
    "source_timezone",
    "raw_expression",
    "time_basis",
    "time_precision",
    "public_ical_revision",
    "human_locked",
    "created_at",
    "updated_at",
  ],
  extraction_runs: [
    "id",
    "article_version_id",
    "extractor",
    "profile_ref",
    "status",
    "usage_json",
    "error",
    "created_at",
    "completed_at",
  ],
  candidates: [
    "id",
    "run_id",
    "event_id",
    "proposal_json",
    "review_status",
    "reviewer",
    "decided_at",
    "decision_reason",
    "created_at",
    "updated_at",
  ],
  evidence: [
    "id",
    "candidate_id",
    "event_id",
    "milestone_id",
    "article_version_id",
    "block_ref",
    "created_at",
  ],
  event_revisions: [
    "id",
    "event_id",
    "revision_no",
    "change_kind",
    "actor_path",
    "reason",
    "diff_json",
    "created_at",
  ],
  // 数据组 3：公共日历
  calendar_projections: [
    "milestone_id",
    "event_id",
    "public_ical_revision",
    "projection_json",
    "updated_at",
  ],
  calendar_patches: [
    "id",
    "milestone_id",
    "patch_kind",
    "old_time_exact_ms",
    "old_time_date",
    "new_time_exact_ms",
    "new_time_date",
    "fact_reason",
    "effective_at",
    "retain_until",
    "superseded_at",
    "created_at",
    "updated_at",
  ],
  public_snapshots: ["id", "generation", "state", "built_at", "published_at", "created_at"],
  public_snapshot_nodes: ["snapshot_id", "milestone_id", "node_json"],
  // 数据组 4：用户
  users: [
    "id",
    "order",
    "status",
    "email_key",
    "email_binding_id",
    "email_ciphertext",
    "email_version",
    "auth_epoch",
    "recovery_epoch",
    "last_interactive_at",
    "last_feed_poll_at",
    "last_push_processed_at",
    "reclaim_grace_until",
    "created_at",
    "updated_at",
  ],
  // 数据组 5：认证
  auth_challenges: [
    "id",
    "purpose",
    "email_key",
    "address_version",
    "preauth_id",
    "idempotency_key",
    "mac",
    "generation",
    "attempts",
    "deadline",
    "reservation_id",
    "consumed_at",
    "aborted_at",
    "receipt_ciphertext",
    "receipt_expires_at",
    "pending_session_id",
    "created_at",
    "updated_at",
  ],
  // 数据组 6：会话与恢复
  sessions: [
    "id",
    "user_id",
    "token_hash",
    "state",
    "label",
    "platform_hint",
    "issued_at",
    "absolute_expires_at",
    "expires_at",
    "renewed_at",
    "auth_epoch",
    "recovery_epoch",
    "activated_at",
    "revoked_at",
    "revoke_reason",
    "created_at",
    "updated_at",
  ],
  recovery_credentials: [
    "id",
    "user_id",
    "secret_hash",
    "generation",
    "consumed_at",
    "saved_confirmed_at",
    "created_at",
    "updated_at",
  ],
  // 数据组 7：云配置
  user_subscriptions: [
    "user_id",
    "state",
    "schema_version",
    "revision",
    "scope_json",
    "calendar_json",
    "notifications_json",
    "created_at",
    "updated_at",
  ],
  subscription_interests: [
    "id",
    "user_id",
    "game",
    "region",
    "interest_kind",
    "interest_id",
    "enabled_at",
  ],
  // 数据组 8：邮件
  email_channels: [
    "user_id",
    "enabled",
    "routine_enabled",
    "consent_version",
    "address_version",
    "lease_expires_at",
    "last_renewed_at",
    "last_renewed_reason",
    "channel_revision",
    "created_at",
    "updated_at",
  ],
  consent_events: [
    "id",
    "user_id",
    "email_binding_id",
    "layer",
    "action",
    "consent_version",
    "context_json",
    "created_at",
  ],
  suppressions: [
    "id",
    "address_key",
    "email_binding_id",
    "kind",
    "read_only",
    "reason",
    "created_at",
    "expires_at",
  ],
  // 数据组 9：Feed
  calendar_feeds: [
    "user_id",
    "namespace",
    "state",
    "token_hash",
    "token_ciphertext",
    "token_generation",
    "view_revision",
    "changed_at",
    "last_feed_poll_at",
    "last_served_node_count",
    "last_served_view_revision",
    "last_served_generation",
    "token_rotated_at",
    "created_at",
    "updated_at",
  ],
  // 数据组 10：Push
  push_bindings: [
    "id",
    "user_id",
    "endpoint_hash",
    "endpoint_ciphertext",
    "keys_ciphertext",
    "state",
    "binding_version",
    "receipt_token_hash",
    "lease_expires_at",
    "activated_at",
    "last_processed_at",
    "created_at",
    "updated_at",
  ],
  // 数据组 11：后台
  jobs: [
    "id",
    "kind",
    "payload_json",
    "due_at",
    "status",
    "lease_version",
    "lease_owner",
    "lease_expires_at",
    "attempts",
    "last_error",
    "created_at",
    "updated_at",
    "completed_at",
  ],
  outbox: [
    "id",
    "topic",
    "dedupe_key",
    "payload_json",
    "dispatch_state",
    "created_at",
    "dispatched_at",
  ],
  occurrences: [
    "id",
    "event_id",
    "milestone_id",
    "schedule_revision",
    "kind",
    "due_at",
    "expires_at",
    "audience_upper_order",
    "backfill",
    "invalidated_at",
    "created_at",
  ],
  // 数据组 12：实际发送
  mail_outbox: [
    "id",
    "purpose",
    "priority",
    "period_key",
    "recipient_user_id",
    "email_binding_id",
    "address_version",
    "payload_kind",
    "payload_ref",
    "payload_ciphertext",
    "status",
    "message_id",
    "lease_version",
    "lease_owner",
    "lease_expires_at",
    "attempts",
    "idempotency_key",
    "sent_at",
    "created_at",
    "updated_at",
  ],
  deliveries: [
    "id",
    "occurrence_id",
    "user_id",
    "channel",
    "target_ref",
    "milestone_id",
    "schedule_revision",
    "rule_id",
    "kind",
    "priority",
    "dedupe_family",
    "mail_outbox_ref",
    "status",
    "skip_reason",
    "expires_at",
    "created_at",
    "updated_at",
  ],
  // 数据组 13：反馈与用量
  mail_feedback: [
    "id",
    "provider_event_id",
    "message_id",
    "mail_outbox_id",
    "kind",
    "feedback_at",
    "raw_ref",
    "created_at",
  ],
  usage_periods: [
    "id",
    "pool",
    "period_kind",
    "period_key",
    "user_id",
    "reserved",
    "settled",
    "uncertain",
    "period_start",
    "period_end",
    "created_at",
    "updated_at",
  ],
  dispatch_cursors: ["pool", "priority", "last_order", "completed_lap", "updated_at"],
  activity_write_failures: ["metric", "utc_day", "failures", "last_success_at", "updated_at"],
  // 数据组 14：容量与管理
  admission_reservations: [
    "id",
    "kind",
    "email_key",
    "state",
    "reserved_at",
    "expires_at",
    "converted_user_id",
    "created_at",
    "updated_at",
  ],
  capacity_state: ["key", "value", "version", "updated_at"],
  system_state: ["key", "value_json", "updated_at"],
  admin_sessions: [
    "id",
    "token_hash",
    "admin_id",
    "issued_at",
    "expires_at",
    "revoked_at",
    "last_used_at",
    "created_at",
  ],
  audit_log: [
    "id",
    "actor_type",
    "actor_id",
    "action",
    "target_type",
    "target_id",
    "reason",
    "detail_ref",
    "created_at",
    "expires_at",
  ],
};

export interface ExpectedIndex {
  table: string;
  columns: readonly string[];
  unique?: boolean;
  /** 部分索引（WHERE 子句）：只校验名称/表/唯一性，列清单跳过（表达式无法从 PRAGMA 还原）。 */
  partial?: boolean;
  /** 表达式索引：列清单含表达式，跳过逐列比对（PRAGMA index_info 对表达式列返回 NULL）。 */
  expression?: boolean;
}

/** 显式 CREATE INDEX（不含 UNIQUE 约束产生的 sqlite_autoindex_*）。 */
export const EXPECTED_INDEXES: Record<string, ExpectedIndex> = {
  idx_sources_game_region: { table: "sources", columns: ["game", "region"] },
  idx_articles_source_last_checked: {
    table: "articles",
    columns: ["source_id", "last_checked_at"],
  },
  idx_article_versions_article: {
    table: "article_versions",
    columns: ["article_id", "version_no"],
  },
  idx_events_catalog: { table: "events", columns: ["game", "region", "event_type", "status"] },
  idx_events_updated: { table: "events", columns: ["updated_at"] },
  idx_milestones_exact: { table: "milestones", columns: ["time_exact_ms"] },
  idx_milestones_date: { table: "milestones", columns: ["time_date"] },
  idx_milestones_event: { table: "milestones", columns: ["event_id"] },
  idx_extraction_runs_article: { table: "extraction_runs", columns: ["article_version_id"] },
  idx_candidates_review_queue: { table: "candidates", columns: ["review_status", "created_at"] },
  idx_evidence_candidate: { table: "evidence", columns: ["candidate_id"] },
  idx_evidence_event: { table: "evidence", columns: ["event_id"] },
  idx_evidence_article_version: { table: "evidence", columns: ["article_version_id"] },
  idx_event_revisions_event: { table: "event_revisions", columns: ["event_id", "revision_no"] },
  idx_calendar_projections_event: { table: "calendar_projections", columns: ["event_id"] },
  idx_calendar_patches_active: {
    table: "calendar_patches",
    columns: ["milestone_id"],
    unique: true,
    partial: true,
  },
  idx_calendar_patches_retention: { table: "calendar_patches", columns: ["retain_until"] },
  idx_calendar_patches_milestone: { table: "calendar_patches", columns: ["milestone_id"] },
  idx_public_snapshots_single_current: {
    table: "public_snapshots",
    columns: ["state"],
    unique: true,
    partial: true,
  },
  idx_public_snapshot_nodes_milestone: {
    table: "public_snapshot_nodes",
    columns: ["milestone_id"],
  },
  idx_users_status_order: { table: "users", columns: ["status", "order"] },
  idx_auth_challenges_email: { table: "auth_challenges", columns: ["email_key", "created_at"] },
  idx_auth_challenges_deadline: { table: "auth_challenges", columns: ["deadline"] },
  idx_auth_challenges_open: { table: "auth_challenges", columns: ["email_key"], partial: true },
  idx_auth_challenges_idem: {
    table: "auth_challenges",
    columns: ["preauth_id", "idempotency_key"],
    unique: true,
    partial: true,
  },
  idx_sessions_owner_state: { table: "sessions", columns: ["user_id", "state"] },
  idx_sessions_expiry_cleanup: { table: "sessions", columns: ["state", "expires_at"] },
  idx_recovery_credentials_current: {
    table: "recovery_credentials",
    columns: ["user_id"],
    unique: true,
    partial: true,
  },
  idx_recovery_credentials_user: {
    table: "recovery_credentials",
    columns: ["user_id", "generation"],
  },
  idx_user_subscriptions_state: { table: "user_subscriptions", columns: ["state"] },
  idx_subscription_interests_user: { table: "subscription_interests", columns: ["user_id"] },
  idx_consent_events_user: { table: "consent_events", columns: ["user_id", "created_at"] },
  idx_consent_events_binding: {
    table: "consent_events",
    columns: ["email_binding_id", "created_at"],
  },
  idx_suppressions_expiry: { table: "suppressions", columns: ["expires_at"], partial: true },
  idx_calendar_feeds_poll: { table: "calendar_feeds", columns: ["last_feed_poll_at"] },
  idx_push_bindings_owner: { table: "push_bindings", columns: ["user_id", "state"] },
  idx_push_bindings_lease: { table: "push_bindings", columns: ["lease_expires_at"] },
  idx_jobs_due: { table: "jobs", columns: ["status", "due_at"] },
  idx_jobs_lease_expiry: { table: "jobs", columns: ["lease_expires_at"] },
  idx_outbox_dispatch: { table: "outbox", columns: ["dispatch_state", "created_at"] },
  idx_occurrences_due: { table: "occurrences", columns: ["due_at"], partial: true },
  idx_occurrences_expiry: { table: "occurrences", columns: ["expires_at"] },
  idx_occurrences_event: { table: "occurrences", columns: ["event_id", "schedule_revision"] },
  idx_mail_outbox_claim: { table: "mail_outbox", columns: ["status", "priority", "created_at"] },
  idx_mail_outbox_lease: { table: "mail_outbox", columns: ["lease_expires_at"] },
  idx_mail_outbox_message_id: {
    table: "mail_outbox",
    columns: ["message_id"],
    unique: true,
    partial: true,
  },
  idx_deliveries_status: { table: "deliveries", columns: ["status", "priority", "expires_at"] },
  idx_deliveries_outbox: { table: "deliveries", columns: ["mail_outbox_ref"] },
  idx_deliveries_owner: { table: "deliveries", columns: ["user_id", "created_at"] },
  idx_deliveries_expiry: { table: "deliveries", columns: ["expires_at"] },
  idx_deliveries_dedupe_components: {
    table: "deliveries",
    columns: ["milestone_id", "schedule_revision", "rule_id", "channel", "target_ref"],
  },
  idx_mail_feedback_message: { table: "mail_feedback", columns: ["message_id"] },
  idx_mail_feedback_outbox: { table: "mail_feedback", columns: ["mail_outbox_id"] },
  idx_usage_periods_identity: {
    table: "usage_periods",
    columns: ["pool", "period_kind", "period_key", "ifnull(user_id, '')"],
    unique: true,
    expression: true,
  },
  idx_usage_periods_period_end: { table: "usage_periods", columns: ["period_end"] },
  idx_admission_reservations_open: {
    table: "admission_reservations",
    columns: ["email_key"],
    unique: true,
    partial: true,
  },
  idx_admission_reservations_expiry: { table: "admission_reservations", columns: ["expires_at"] },
  idx_admin_sessions_expiry: { table: "admin_sessions", columns: ["expires_at"] },
  idx_audit_log_expiry: { table: "audit_log", columns: ["expires_at"] },
  idx_audit_log_created: { table: "audit_log", columns: ["created_at"] },
};

/** 合同级承载唯一性的 UNIQUE 约束（sqlite_autoindex_*，经 PRAGMA index_list origin='u' 校验）。 */
export const EXPECTED_UNIQUE_CONSTRAINTS: Record<string, readonly string[][]> = {
  articles: [["source_id", "external_id"]],
  article_versions: [
    ["article_id", "version_no"],
    ["article_id", "content_hash"],
  ],
  milestones: [["event_id", "milestone_key"]],
  extraction_runs: [["article_version_id", "extractor", "profile_ref"]],
  event_revisions: [["event_id", "revision_no"]],
  public_snapshots: [["generation"]],
  users: [["email_key"], ["email_binding_id"], ["order"]],
  sessions: [["token_hash"]],
  subscription_interests: [["user_id", "game", "region", "interest_kind", "interest_id"]],
  suppressions: [["address_key"]],
  calendar_feeds: [["namespace"], ["token_hash"]],
  push_bindings: [["endpoint_hash"], ["receipt_token_hash"]],
  outbox: [["dedupe_key"]],
  occurrences: [["milestone_id", "schedule_revision", "kind"]],
  mail_outbox: [["idempotency_key"]],
  deliveries: [["dedupe_family"]],
  mail_feedback: [["provider_event_id"]],
};

/** 不变式触发器（合同显式不变式的数据库层落点）。 */
export const EXPECTED_TRIGGERS: readonly string[] = [
  "trg_article_versions_immutable",
  "trg_sessions_absolute_expires_immutable",
  "trg_user_subscriptions_state_oneway",
  "trg_calendar_feeds_namespace_immutable",
];

/** AGENTS.md 禁止清单对象：schema 里出现即不合格。 */
export const FORBIDDEN_NAME_FRAGMENTS: readonly string[] = [
  "feed_retirements",
  "calendar_change_no",
  "removal_change_no",
];

/** 三类业务版本量必须分列存在，禁止合并成一个计数器（ENGINEERING.md §5.2）。 */
export const SEPARATE_VERSION_COLUMNS: Readonly<Record<string, readonly string[]>> = {
  events: ["event_revision", "schedule_revision"],
  milestones: ["public_ical_revision"],
};

export interface EnumCheckSource {
  /** contracts：值来自 packages/contracts 单一定义源，测试逐值比对。 */
  values: readonly string[];
  source: string;
}

/** CHECK 枚举同步清单：table.column → 期望取值集合。 */
export const EXPECTED_ENUM_CHECKS: Record<string, EnumCheckSource> = {
  "events.event_type": { values: EVENT_TYPES, source: "contracts:EVENT_TYPES" },
  "events.status": { values: EVENT_STATUSES, source: "contracts:EVENT_STATUSES" },
  "milestones.node_type": { values: NODE_TYPES, source: "contracts:NODE_TYPES" },
  "milestones.time_basis": { values: TIME_BASES, source: "contracts:TIME_BASES" },
  "milestones.time_precision": { values: TIME_PRECISIONS, source: "contracts:TIME_PRECISIONS" },
  "candidates.review_status": { values: REVIEW_STATUSES, source: "contracts:REVIEW_STATUSES" },
  "sessions.state": { values: SESSION_STATUSES, source: "contracts:SESSION_STATUSES" },
  "user_subscriptions.state": {
    values: SUBSCRIPTION_STATES,
    source: "contracts:SUBSCRIPTION_STATES",
  },
  "deliveries.status": { values: DELIVERY_STATUSES, source: "contracts:DELIVERY_STATUSES" },
  "mail_outbox.status": { values: DELIVERY_STATUSES, source: "contracts:DELIVERY_STATUSES" },
  // 以下为合同正文枚举但尚未收编进 packages/contracts 的字面值（标注出处；
  // 后续任务卡（P1-03/P1-07）收编时应改为 contracts 引用）。
  "usage_periods.pool": {
    values: ["existing_auth", "new_registration", "base_business", "urgent_business"],
    source: "主方案 §9.1 四池（待收编 contracts）",
  },
};

/** 必须出现在表 DDL 里的合同不变式子串（正则）。 */
export const EXPECTED_DDL_INVARIANTS: ReadonlyArray<{
  table: string;
  pattern: RegExp;
  note: string;
}> = [
  {
    table: "sessions",
    pattern: /CHECK\s*\(\s*expires_at\s*<=\s*absolute_expires_at\s*\)/,
    note: "§4.5 低频续期不得突破抖动后绝对期限",
  },
  {
    table: "user_subscriptions",
    pattern: /state\s*=\s*'uninitialized'\s*OR\s*\(/,
    note: "§5.1 scope/calendar.event_types 非空约束只对 initialized 成立",
  },
  {
    table: "email_channels",
    pattern: /CHECK\s*\(\s*routine_enabled\s*=\s*0\s*OR\s*enabled\s*=\s*1\s*\)/,
    note: "§7.5 routine 层是席位层的子集",
  },
  {
    table: "milestones",
    pattern:
      /time_precision\s*=\s*'datetime'\s*AND\s*time_exact_ms\s*IS\s*NOT\s*NULL\s*AND\s*time_date\s*IS\s*NULL/,
    note: "§3.3 时间精度与存值形态一一对应，只有日期不补午夜",
  },
  {
    table: "mail_outbox",
    pattern: /CHECK\s*\(\s*priority\s+BETWEEN\s+0\s+AND\s+5\s*\)/,
    note: "§7.3 优先级阶梯 0=认证 … 5=新公布",
  },
  {
    table: "deliveries",
    pattern: /CHECK\s*\(\s*priority\s+BETWEEN\s+1\s+AND\s+5\s*\)/,
    note: "§7.3 业务优先级阶梯五档",
  },
];

/** 任务卡明确要求"必须出现"的列（漏掉后面补很贵）。 */
export const MANDATORY_COLUMNS: Readonly<Record<string, readonly string[]>> = {
  sessions: [
    "absolute_expires_at",
    "expires_at",
    "renewed_at",
    "label",
    "auth_epoch",
    "recovery_epoch",
  ],
  user_subscriptions: ["state"],
  email_channels: [
    "enabled",
    "routine_enabled",
    "lease_expires_at",
    "last_renewed_reason",
    "channel_revision",
  ],
  calendar_feeds: [
    "namespace",
    "view_revision",
    "token_hash",
    "token_ciphertext",
    "token_generation",
    "last_feed_poll_at",
    "last_served_node_count",
    "last_served_view_revision",
    "last_served_generation",
  ],
  deliveries: ["dedupe_family", "priority", "mail_outbox_ref"],
  usage_periods: ["pool", "period_kind", "period_key", "reserved", "settled", "uncertain"],
  recovery_credentials: ["generation", "consumed_at", "saved_confirmed_at"],
};
